package com.ticketmaster.ticketing_engine.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * <h1>Event Entity</h1>
 * <p>
 * Represents a specific concert, game, or show in the database.
 * This class maps directly to the {@code events} table.
 * </p>
 * <h2>Concurrency Control:</h2>
 * <p>
 * This entity uses <b>Optimistic Locking</b> (via the {@code @Version} field).
 * This ensures that if 10,000 users try to buy the last ticket simultaneously,
 * the database will only allow one transaction to succeed, preventing overbooking.
 * </p>
 */
@Entity
@Table(name = "events")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Event {

    /**
     * Unique ID for the event. Auto-generated by the database.
     */
    @Schema(description = "Unique Event ID", example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the event (e.g., "Taylor Swift - Eras Tour").
     */
    @Schema(description = "Name of the event", example = "Coldplay Music of the Spheres")
    private String name;

    /**
     * The date and time when the event starts.
     */
    @Schema(description = "Date and time of the event", example = "2025-06-15T20:00:00")
    private LocalDateTime date;

    /**
     * The venue name or city.
     */
    @Schema(description = "Venue location", example = "Wembley Stadium, London")
    private String location;

    /**
     * Cost per single ticket.
     */
    @Schema(description = "Price per ticket", example = "150.00")
    private double ticketPrice;

    /**
     * The total capacity of the venue.
     * This number never changes after creation.
     */
    @Schema(description = "Total capacity (Max tickets)", example = "50000")
    private int totalTickets;

    /**
     * The number of tickets currently remaining.
     * <p>
     * This decreases every time a user calls the {@code /buy} endpoint.
     * Logic: {@code availableTickets = availableTickets - 1}
     * </p>
     */
    @Schema(description = "Tickets currently left to sell", example = "450")
    private int availableTickets;

    /**
     * Version number for Optimistic Locking.
     * <p>
     * Hibernate automatically increments this number on every update.
     * If two threads try to update the same version, one will fail with
     * {@code ObjectOptimisticLockingFailureException}.
     * </p>
     */
    @Schema(description = "Internal version for concurrency control", example = "0")
    @Version
    private Long version;


}
