package com.ticketmaster.event.entity;

import com.ticketmaster.event.util.Category;
import com.ticketmaster.event.util.Status;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * <h1>Event Entity</h1>
 * <p>
 * Represents a specific concert, game, or show in the database.
 * This class maps directly to the {@code events} table.
 * </p>
 * <h2>Concurrency Control:</h2>
 * <p>
 * This entity uses <b>Optimistic Locking</b> (via the {@code @Version} field).
 * This ensures that if 10,000 users try to buy the last ticket simultaneously,
 * the database will only allow one transaction to succeed, preventing overbooking.
 * </p>
 */
@Entity
@Table(name = "events")
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Event {

    /**
     * Unique ID for the event. Auto-generated by the database.
     */
    @Schema(description = "Unique Event ID", example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the event.
     */
    @Schema(description = "Name of the event", example = "Coldplay Music of the Spheres")
    @NotBlank(message = "Event name is required")
    private String name;

    /**
     * A brief description of the event.
     */
    @Schema(description = "Description of the event")
    @NotBlank(message = "Description is required")
    private String description;

    /**
     * The date and time when the event starts.
     */
    @Schema(description = "Date and time of the event", example = "2025-06-15T20:00:00")
    @NotNull(message = "Event date is required")
    @Future(message = "Event date must be in the future")
    private LocalDateTime date;

    /**
     * The venue name or city.
     */
    @Schema(description = "Venue location", example = "10")
    @NotNull(message = "Location is required")
    private Long venueId;


    /**
     * The performer or team associated with the event.
     */
    @Schema(description = "Preformer", example = "5")
    @NotNull(message = "Preformer is required")
    private Long performerId;

    /**
     * Cost per single ticket.
     */
    @Schema(description = "Price per ticket", example = "150.00")
    @Min(value = 0, message = "Ticket price must be positive")
    private double ticketPrice;

    /**
     * The total capacity of the venue.
     * This number never changes after creation.
     */
    @Schema(description = "Total capacity (Max tickets)", example = "50000")
    @Min(value = 1, message = "Total tickets must be at least 1")
    private int totalTickets;

    /**
     * The number of tickets currently remaining.
     * <p>
     * This decreases every time a user calls the {@code /buy} endpoint.
     * Logic: {@code availableTickets = availableTickets - 1}
     * </p>
     */
    @Schema(description = "Tickets currently left to sell", example = "450")
    private int availableTickets;

    /**
     * Version number for Optimistic Locking.
     * <p>
     * Hibernate automatically increments this number on every update.
     * If two threads try to update the same version, one will fail with
     * {@code ObjectOptimisticLockingFailureException}.
     * </p>
     */
    @Schema(description = "Internal version for concurrency control", example = "0")
    @Version
    private Long version;


    @Schema(description = "Status of the event", example = "SCHEDULED", allowableValues = {"SCHEDULED", "UPCOMING", "CANCELLED", "COMPLETED"})
    @NotNull(message = "Status is required")
    @Enumerated(EnumType.STRING)
    private Status status;


    @Schema(description = "Category of the event", example = "MUSIC")
    @NotNull(message = "Category is required")
    @Enumerated(EnumType.STRING)
    private Category category;

    /**
     * Timestamp when this event was first created in the database.
     * <p>
     * This field is automatically set by JPA when the entity is persisted for the first time.
     * It will NEVER change after creation.
     * </p>
     */
    @Schema(description = "When the event was created in the system", example = "2026-01-01T10:00:00")
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this event was last updated.
     * <p>
     * This field is automatically updated by JPA whenever the entity is modified.
     * </p>
     */
    @Schema(description = "When the event was last updated", example = "2026-01-15T14:30:00")
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Automatically sets createdAt and updatedAt before persisting a new event.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Automatically updates the updatedAt field before updating an existing event.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

}
